apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: monitoring
  labels:
    type: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  # 변경: 여러 노드에서 동시에 읽고 쓸 수 있어야 합니다.
  nfs:
    path: /srv/nfs  # 변경: NFS 서버에서 공유하는 경로로 변경합니다.
    server: 192.168.50.56  # 변경: NFS 서버의 IP 주소로 변경합니다.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # 변경: 여러 노드에서 동시에 읽고 쓸 수 있어야 합니다.
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs  # 변경: PersistentVolume에서 정의한 레이블로 변경합니다.

